### ISSUE TITLE
Make more issues

### ISSUE THREAD

**Issue by ahnaf-zamil** [HuyaneMatsu/hata#18]
New contributors don't have anything to work on. So just make some issues which we can contribute to

**Comment by HuyaneMatsu** [comment]
Consider the [Projects](https://github.com/HuyaneMatsu/hata/projects/2) tab as a collection of issues on which new contributors could work on.

If you have an ideas of improvements, then your best way to commit is by sharing them. Since most the things added to the wrapper are based on my use cases, I gladly accept reasoned ideas to implement.

My explanation skills are really bad, so I mostly  accept help at improving the /docs part of the project. I opened a To-Do (but docs) column for this reason. Hoping they will be resolved and more notes will be added to it as well in the future.

**Comment by asianmancoder** [comment]
Amen.
