### ISSUE TITLE
[Bug] Interaction has already been acknowledged.

### ISSUE THREAD

**Issue by Ruochenfu2011** [HuyaneMatsu/hata#80]
### Description

Interaction has already been acknowledged.

### Expected behaviour

Been Normal

### System information

Newest

**Comment by HuyaneMatsu** [comment]
I am sorry, but the reproduction steps are insufficient to reproduce the issue. The expected behavior and the system information are also both vague.

I recommend you to check whether you have the same bot running multiple times. Multiple instances of the same bot can cause race condition when acknowledging an interaction leading one of them dropping an error of this reason.

**Comment by HuyaneMatsu** [comment]
Closing.
